# Site settings
title:
email: banninghardscapes@gmail.com
phone: 302-420-3476

description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://banninghardscapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
